---
- name: Add NICs to {{ tier_1_rtr_sea }}
  community.vmware.vmware_guest_network:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ tier_1_rtr_sea }}"
    state: present
    network_name: "{{ item.network_name | default(omit) }}"
    connected: true
  loop:
    - { label: eth0, network_name: "Range Operations", state: present }
    - { label: eth1, network_name: "CDX - Tier 2 - Seattle", state: present }
    - { label: eth2, network_name: "CDX - Tier 1 - Americas", state: present }