---
- name: Initialize Terraform Environment
  import_tasks: ../common/tasks/terraform_init.yml    # 'terraform init''

- name: Apply Terraform Configuration
  import_tasks: ../common/tasks/terraform_apply.yml    # 'terraform apply''