---
- name: Power Off Internet Routers
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ item }}"
    state: powered-off
    state_change_timeout: 200
  delegate_to: localhost
  register: deploy
  with_items:
    - "{{ core_rtr_1 }}"
    - "{{ core_rtr_2 }}"
    - "{{ core_rtr_3 }}"
    - "{{ tier_1_rtr_ams }}"
    - "{{ tier_1_rtr_syd }}"
    - "{{ tier_1_rtr_sea }}"
    - "{{ tier_1_rtr_tor }}"
    - "{{ tier_1_rtr_de }}"
    - "{{ tier_1_rtr_vlv }}"
    - "{{ tier_1_rtr_dxb }}"
    - "{{ tier_1_rtr_br }}"
    - "{{ tier_1_rtr_icn }}"
    - "{{ tier_1_rtr_lon }}"